---
- name: Install Docker, CRI-Dockerd, and Kubernetes packages
  hosts: all
  become: true
  vars:
    link: "https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.15/cri-dockerd_0.3.15.3-0.ubuntu-jammy_amd64.deb"
  tasks:
    - name: Update APT package index
      apt:
        update_cache: true

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Create directory for APT keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's official GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      changed_when: false

    - name: Add Docker repository to APT sources
      command: >
        sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list'
      changed_when: false

    - name: Update APT package index again
      apt:
        update_cache: true

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Download CRI-Dockerd package
      get_url:
        url: "{{ link }}"
        dest: /tmp/cri-dockerd.deb

    - name: Install CRI-Dockerd package
      command: dpkg -i /tmp/cri-dockerd.deb
      changed_when: false

    - name: Download Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /tmp/kubernetes-apt-keyring.gpg

    - name: Save Kubernetes GPG key
      command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes repository to APT sources
      copy:
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'

    - name: Update APT package index for Kubernetes
      apt:
        update_cache: true

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold Kubernetes packages
      command: apt-mark hold kubelet kubeadm kubectl
      changed_when: false

    - name: Disable swap
      command: sudo swapoff -a
      changed_when: false

    - name: Comment out swap in /etc/fstab
      command: sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      changed_when: false

    - name: Load overlay kernel module
      command: sudo modprobe overlay
      changed_when: false

    - name: Load br_netfilter kernel module
      command: sudo modprobe br_netfilter
      changed_when: false

    - name: Configure sysctl for Kubernetes
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/k8s.conf
        mode: '0644'

    - name: Apply sysctl settings
      command: sudo sysctl --system
      changed_when: false